### ISSUE TITLE
Exclude TypoScript files

### ISSUE THREAD

**Issue by ajafff** [urish/bigtsquery#6]
I just tried searching uses of the exponentiation operator `**`: https://bigtsquery.firebaseapp.com/query?selector=AsteriskAsteriskToken

The result only contains false positives, because Typ**o**Script seems to use the same `.ts` extension. Is there any chance you can exclude such files?
Maybe just a blacklist of known typo3 repositories?

**Comment by urish** [comment]
Funny,  I didn't even know typo3 was a thing :)

Is there any specific text I can use for filtering these out? I ran a quick query for the text `INCLUDE_TYPOSCRIPT` and found 61 matches.

**Comment by ajafff** [comment]
> I ran a quick query for the text INCLUDE_TYPOSCRIPT and found 61 matches.

I think that might be the easiest solution. A quick look at the official docs doesn't show any specific prologue for this kind of file.

**Comment by urish** [comment]
Seems like Blacklist did the trick better
